version: '3.9'

services:
  postgres:
    image: postgres:17.6
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: aaa
    volumes:
      # this volume is in host machine and will not be destroyed with container, replcae (./volume) with your own path of volume if needed
      - ./volume:/var/lib/postgresql/data
      # - postgres_data:/var/lib/postgresql/data # this volume is in container and will be detroyed with container
    ports:
      - "5432:5432"
volumes:
  postgres_data: